CommandNotFound = '``[ERROR] Command could not be found!``'
ChannelNotFound = '``[ERROR] Channel could not be found!``'
NickPermission = '``[ERROR] No permission to change nicknames!``'
RolePermission = '``[ERROR] No permission to add roles!``'
InvalidFormat = '``[ERROR] Invalid Format!``'